/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PersonCity } from './PersonCity';
import { HttpFile } from '../http/http';

export class Person {
    'id'?: number;
    /**
    * the first name of the person
    */
    'firstName'?: string;
    /**
    * the last name of the person
    */
    'lastName'?: string;
    'city': PersonCity;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "PersonCity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Person.attributeTypeMap;
    }
    
    public constructor() {
    }
}

